name: Get medium blog posts

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get medium posts
        uses: SharmilaS22/medium-feed-actions@main
        with:
          username: SharmilaS

      - name: Get medium posts
        run: |
          curl https://api.rss2json.com/v1/api.json?rss_url=https://medium.com/feed/@sharmilas

