name: React build

on:
  push:
    branches:
      - main
      - 'feat/**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install npm modules
        run: npm ci

      - name: Build the node app
        run: npm run build --if-present

      - name: Testing
        run: npm test
